### ISSUE TITLE
汉字格言不是分条出现而是整个文本一起出现

### ISSUE THREAD

**Issue by ugoa** [ruanyf/fortunes#1]
![screen shot 2015-04-14 at 11 29 19 am](https://cloud.githubusercontent.com/assets/1934726/7129899/93c5982e-e299-11e4-9a22-809035440758.png)

像这样。
环境 mac os x 10.9.3
iterm + zsh

**Comment by ruanyf** [comment]
我试一下再说，有可能是Mac的换行符与Linux不同。

**Comment by ruanyf** [comment]
确认不是因为换行符的问题，估计Mac平台需要单独生成dat索引文件，不知道 strfile 命令在Mac平台是否可用。

我手边没有 Mac，只能等等再解决了。

**Comment by ruanyf** [comment]
能够运行一下strfile，告诉我结果吗？

可以在`fortune/data`目录中，运行下面命令。

``` bash
$ strfile song100
```

**Comment by kk17** [comment]
我在Mac上同样遇到这样的问题，运行`strfile song100`得到下面的结果：

```
"song100.dat" created
There were 95 strings
Longest string: 955 bytes
Shortest string: 175 bytes
```

发现对文件运行strfile命令之后格式正确了

**Comment by ugoa** [comment]
:+1:
