### ISSUE TITLE
整理英文 fortunes

### ISSUE THREAD

**Issue by jakwings** [ruanyf/fortunes#11]
我将那个包含英文箴言的文件 `fortunes` 重新整理了一下放在这了：
https://github.com/jakwings/cookies (`misc`)

主要是去除不影响韵律的强制换行（改由 `fold --width=N` 自动处理），移除 Unknown 之类比较没意义的来源说明，去重，改善标点和统一排版。若是有需要我可以发个 PR。也对中文内容做了类似整理，不过没上传。

**Comment by ruanyf** [comment]
我合并进去了。多谢。

中文 Cookie 的那个文件，数据有点问题，不少句子不完整，不整理也没关系。

**Comment by jakwings** [comment]
😅 才发现你把前面几行也加进去了：

```
%% Origin: https://github.com/ruanyf/fortunes
%% Modification: Remove line wraps & Unify punctuation & Improve layout.
%% Authenticity: Don't care.
%
```

得在生成索引时启用注释功能才会忽略这几行。

**Comment by ruanyf** [comment]
谢谢提醒，我疏忽了。已经删除这些多余的行了。

**Comment by codecoron** [comment]
请问一下，这个在centos下可以运行吗？我试了一下，把data下的文件复制到` /usr/share/games/fortune/ `不太行，报错说`fortune: no fortune found`。

我稍微对比了一下，复制过去的和原来就有的。比如chinese和work，work是原来就有的。work可以直接双击打开，而chinese双击会报错，说未知文件类型。我觉得这就是关键所在。求解答(-_-)

**Comment by jakwings** [comment]
@codecoron `chinese` 和 `chinese.dat` 都复制了吗？要是装了 `strace` 可以看看 `strace fortune chinese` 的输出

**Comment by codecoron** [comment]
@iology  你好，我用Linux记事本对比了一下复制过去的和原来就有的，发现原来就有的，每个条目都被 一对%% 包括，复制过去的，最上面是少了一个%。于是我就加上了一个%，再用strfile ，发现居然可以了
