### ISSUE TITLE
show Chinese data wrong with brew on OSX

### ISSUE THREAD

**Issue by sangshuduo** [ruanyf/fortunes#2]
$ brew -v
Homebrew 0.9.5

$ brew info fortune
fortune: stable 9708 (bottled)
http://ftp.ibiblio.org/pub/linux/games/amusements/fortune/!INDEX.html
/usr/local/Cellar/fortune/9708 (122 files, 7.0M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fortune.rb
==> Options
--without-offensive
    Don't install potentially offensive fortune files

Reproduce steps:
1, brew install fortunes.
2, git clone ...
3, mv data to /usr/local/share/games/fortunes
4, fortune -e fortunes chinese tang300 song100
5, fortune

Output:
fortune will output English data right.
but seems output all Chinese content with '%'.

**Comment by ruanyf** [comment]
Please check README.

``` bash
# Mac
$ git clone git@github.com:ruanyf/fortunes.git
$ strfile fortunes/data/fortunes
$ strfile fortunes/data/chinese
$ strfile fortunes/data/tang300
$ strfile fortunes/data/song100
$ sudo mv fortunes/data/* /usr/share/games/fortunes/
```

In short, you have to re-index the data files before moving them.

**Comment by sangshuduo** [comment]
thanks for your tip
